### ISSUE TITLE
路径写死换了后台路径不能用

### ISSUE THREAD

**Issue by benzBrake** [DT27/SlantedExtend#1]
``` php
        Typecho_Plugin::factory('admin/write-page.php')->bottom = array('SlantedExtend_Plugin', 'headingJS');
        //文章缩略图
        Typecho_Plugin::factory('admin/write-post.php')->bottom = array('SlantedExtend_Plugin', 'thumbJS');
        //原创文章
        Typecho_Plugin::factory('admin/write-post.php')->option = array('SlantedExtend_Plugin', 'originalHtml');
        //原创文章
        Typecho_Plugin::factory('admin/write-post.php')->bottom = array('SlantedExtend_Plugin', 'originalJS');
        //浏览量统计
        Typecho_Plugin::factory('Widget_Archive')->beforeRender = array('SlantedExtend_Plugin', 'viewsCounter');
```

另外如果我想往admin/login.php 插入css和js，我仿造你的写的，貌似起不了作用`Typecho_Plugin::factory('admin/login.php')->bottom = array('Login_Plugin', 'external');`

**Comment by DT27** [comment]
@Char1sma 插入页面要求原页面里有插入点。
我找了下，admin/login.php 里没有插入点。
admin/footer.php 里有个`Typecho_Plugin::factory('admin/footer.php')->end();`，这就是一个插入点。
用法：`Typecho_Plugin::factory('admin/footer.php')->end = array('Login_Plugin', 'external');`
admin/header.php里也有一个。

**Comment by benzBrake** [comment]
谢谢，在官方文档找到说明了，确实得有声明方法才能插入http://docs.typecho.org/plugins/hooks
